language: python

python:
  - "3.6"

services:
  - postgresql

# addons: 
#   postgresql: “9.6”

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.6

install:
  - pip install pipenv
  - pipenv install

before_script:
    - cp immocool/settings/database.yml.travis immocool/settings/database.yml

env:
    global:
    - PGPORT=5433
    -  DJANGO_SETTINGS_MODULE="immocool.settings.travis"

script:
  - ./manage.py test
