language: python

python:
  - "3.6"

services:
  - postgresql

# before_script:

install:
  - pip install pipenv
  - pipenv install
  # - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
  - DJANGO_SETTINGS_MODULE="immocool.settings.travis"

addons: 
  postgresql: “9.6”


script:
  - ./manage.py test --DJANGO_SETTINGS_MODULE="immocool.settings.travis"
