language: python

python:
  - "3.6"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

install:
  - pip install pipenv
  - pipenv install

env:
  global:
  - DJANGO_SETTINGS_MODULE="immocool.settings.travis"

services:
  - postgresql

addons: 
  postgresql: “9.6”


script:
  - ./manage.py test --DJANGO_SETTINGS_MODULE="immocool.settings.travis"
