language: python

python:
  - "3.6"

install:
  - 'pip install pipenv'
  - 'pipenv install'

env:
  - DJANGO_SETTINGS_MODULE="purbeurre_project.settings.travis"
  - SECRET_KEY=ck8k8bz%=jqxg(sqxax_!na5!s0nd$a2#equmxqneod5aq4)w+

services:
  - postgresql

script:
  - ./manage.py test
