language: python

python:
  - "3.6"

services:
  - postgresql

addons: 
  postgresql: “9.6”

# before_script:

install:
  - pip install pipenv
  - pipenv install
  # - psql -c 'create database travis_ci_test;' -U postgres

env: DJANGO_SETTINGS_MODULE="immocool.settings.travis"


script:
  - ./manage.py test
