language: python

python:
  - "3.6"

install:
  - 'pip install pipenv'
  - 'pipenv install'

env:
  global:
  - DJANGO_SETTINGS_MODULE="immocool.settings.travis"

services:
  - postgresql

addons: 
  postgresql: “9.6”

script:
  - ./manage.py test
