# Generated by Django 2.2.1 on 2019-05-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('quittance', '0001_initial'),
        ('occupant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupency', models.BooleanField(default=False)),
                ('superficy', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('number_of_bedroom', models.DecimalField(decimal_places=0, max_digits=2)),
                ('superficy', models.DecimalField(decimal_places=2, max_digits=3)),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_property', to='home.Administrator', verbose_name='related administrator')),
                ('bedroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom_property', to='rental.Bedroom', verbose_name='bedroom in property')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('archived', models.BooleanField()),
                ('bedroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom_rental', to='rental.Bedroom', verbose_name='bedroom for rental')),
                ('occupant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupant_rental', to='occupant.Occupant', verbose_name='occupant of rental')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_rental', to='rental.Property', verbose_name='property for rental')),
                ('quittance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittance_rental', to='quittance.Quittance', verbose_name='quittance for rental')),
            ],
        ),
    ]
