# Generated by Django 2.2.1 on 2019-05-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20190517_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rental',
            name='quittance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quittance_rental', to='quittance.Quittance', verbose_name='quittance for rental'),
        ),
    ]
