# Generated by Django 2.2.1 on 2019-05-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20190517_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='administrator_id',
            new_name='administrator',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bedroom_id',
            new_name='bedroom',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='bedroom_id',
            new_name='bedroom',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='occupant_id',
            new_name='occupant',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='quittance_id',
            new_name='quittance',
        ),
    ]
