# Generated by Django 2.2.1 on 2019-05-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_remove_rental_quittance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bedroom',
        ),
        migrations.AddField(
            model_name='bedroom',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_bedroom', to='rental.Property', verbose_name='property for bedroom'),
        ),
    ]
