# Generated by Django 2.2.1 on 2019-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_auto_20190527_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='charges',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
