# Generated by Django 2.2.1 on 2019-05-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEventEcheance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventEcheance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=250)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_event', to='event.TypeEventEcheance', verbose_name='type of event')),
            ],
        ),
    ]
