# Generated by Django 2.2.1 on 2019-05-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_doc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_type_of', to='occupant.TypeDocument', verbose_name='related document type'),
        ),
    ]
