# Generated by Django 2.2.1 on 2019-05-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupant', '0002_auto_20190517_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='date_of_leaving',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='deposit',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='occupant.Document', verbose_name='related document'),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
