# Generated by Django 2.2.1 on 2019-05-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupant', '0003_auto_20190517_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='doc_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='occupant.Document', verbose_name='related document'),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='suivi',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
