# Generated by Django 2.2.1 on 2019-05-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupant', '0005_remove_occupant_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='occupant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_of', to='occupant.Occupant'),
        ),
    ]
