# Generated by Django 2.2.1 on 2019-05-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupant', '0006_auto_20190521_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='occupant_id',
            new_name='occupant',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='type_doc_id',
            new_name='type_doc',
        ),
        migrations.RenameField(
            model_name='occupant',
            old_name='user_id',
            new_name='user',
        ),
    ]
