# Generated by Django 2.2.1 on 2019-05-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='user_id',
            new_name='user',
        ),
    ]
