# Generated by Django 2.2.1 on 2019-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190523_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='address',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
