# Generated by Django 2.2.1 on 2019-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('monthly_rent_paid', models.BooleanField(default=False)),
                ('date_of_payment', models.DateField()),
            ],
        ),
    ]
