# Generated by Django 2.2.1 on 2019-05-23 21:33

from django.db import migrations, models
import quittance.models


class Migration(migrations.Migration):

    dependencies = [
        ('quittance', '0002_auto_20190516_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quittance',
            old_name='bedroom_id',
            new_name='bedroom',
        ),
        migrations.RenameField(
            model_name='quittance',
            old_name='occupant_id',
            new_name='occupant',
        ),
        migrations.RenameField(
            model_name='quittance',
            old_name='property_id',
            new_name='property',
        ),
        migrations.AddField(
            model_name='quittance',
            name='quittance',
            field=models.FileField(blank=True, upload_to=quittance.models.quittance_directory_path),
        ),
    ]
