# Generated by Django 2.2.1 on 2019-05-24 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_remove_rental_quittance'),
        ('quittance', '0003_auto_20190523_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='rental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_quittances', to='rental.Rental', verbose_name='related rental'),
        ),
    ]
