# Generated by Django 2.2.1 on 2019-05-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quittance', '0005_auto_20190527_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quittance',
            old_name='date_of_payment',
            new_name='date_of_issue',
        ),
        migrations.RemoveField(
            model_name='quittance',
            name='date',
        ),
    ]
