# Generated by Django 2.2.1 on 2019-06-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quittance', '0006_auto_20190528_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quittance',
            name='bedroom',
        ),
        migrations.RemoveField(
            model_name='quittance',
            name='occupant',
        ),
        migrations.RemoveField(
            model_name='quittance',
            name='property',
        ),
    ]
