# Generated by Django 2.2.1 on 2019-06-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quittance', '0007_auto_20190603_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittance',
            name='quittance',
            field=models.FileField(blank=True, upload_to='quittances_pdf/'),
        ),
    ]
