# Generated by Django 2.2.1 on 2019-06-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_rental_charges'),
        ('quittance', '0008_auto_20190610_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echeance', models.FileField(blank=True, upload_to='echeances_pdf/')),
                ('date_of_issue', models.DateField(blank=True)),
                ('rental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_echeances', to='rental.Rental', verbose_name='related rental_echeances')),
            ],
        ),
    ]
