# Generated by Django 2.2.1 on 2019-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quittance', '0009_echeance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quittance',
            name='monthly_rent_paid',
        ),
        migrations.AddField(
            model_name='echeance',
            name='monthly_rent_paid',
            field=models.BooleanField(default=False),
        ),
    ]
